config/routes.rb
Rails.application.routes.draw do
  resources :friends_rankings
  resources :discount_votes
  resources :user_location_changes
  resources :user_searches
  resources :discount_searches
  resources :user_sessions, only: [:create, :update]
  resources :friendships
  resources :discounts
  resources :settings
  resources :users

  # Routes for testing
  if Rails.env.test?
    post 'test' => 'testing#test'
    get  'test' => 'testing#test'
  end
end

app/models/user_location_change.rb
class UserLocationChange < ActiveRecord::Base
  belongs_to :user
  belongs_to :location

  validates_presence_of :user, :location

  accepts_nested_attributes_for :location

  after_create :set_user_location

  def set_user_location
    user.location = location
    user.save
  end
end

app/controllers/user_location_changes_controller.rb
class UserLocationChangesController < ApplicationController
  before_action :check_user_session
  before_action :set_user_location_change, only: [:show, :edit, :update, :destroy]

  # GET /user_location_changes
  # GET /user_location_changes.json
  def index
    @user_location_changes = UserLocationChange.all
  end

  # GET /user_location_changes/1
  # GET /user_location_changes/1.json
  def show
  end

  # GET /user_location_changes/new
  def new
    @user_location_change = UserLocationChange.new
  end

  # GET /user_location_changes/1/edit
  def edit
  end

  # POST /user_location_changes
  # POST /user_location_changes.json
  def create
    @user_location_change = UserLocationChange.new(user_location_change_params)

    respond_to do |format|
      if @user_location_change.save
        format.html { redirect_to @user_location_change, notice: 'User location change was successfully created.' }
        format.json { render :show, status: :created, location: @user_location_change }
      else
        format.html { render :new }
        format.json { render json: @user_location_change.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_location_changes/1
  # PATCH/PUT /user_location_changes/1.json
  def update
    respond_to do |format|
      if @user_location_change.update(user_location_change_params)
        format.html { redirect_to @user_location_change, notice: 'User location change was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_location_change }
      else
        format.html { render :edit }
        format.json { render json: @user_location_change.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_location_changes/1
  # DELETE /user_location_changes/1.json
  def destroy
    @user_location_change.destroy
    respond_to do |format|
      format.html { redirect_to user_location_changes_url, notice: 'User location change was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_location_change
      @user_location_change = UserLocationChange.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_location_change_params
      params.require(:user_location_change).permit(:user_id, location_attributes: [:lat, :lng])
    end
end

app/helpers/user_location_changes_helper.rb
module UserLocationChangesHelper
end

app/views/user_location_changes/_form.html.erb
<%= form_for(@user_location_change) do |f| %>
  <% if @user_location_change.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_location_change.errors.count, "error") %> prohibited this user_location_change from being saved:</h2>

      <ul>
      <% @user_location_change.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_location_changes/edit.html.erb
<h1>Editing User Location Change</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_location_change %> |
<%= link_to 'Back', user_location_changes_path %>

app/views/user_location_changes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Location Changes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_location_changes.each do |user_location_change| %>
      <tr>
        <td><%= user_location_change.user %></td>
        <td><%= user_location_change.location %></td>
        <td><%= link_to 'Show', user_location_change %></td>
        <td><%= link_to 'Edit', edit_user_location_change_path(user_location_change) %></td>
        <td><%= link_to 'Destroy', user_location_change, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User location change', new_user_location_change_path %>

app/views/user_location_changes/new.html.erb
<h1>New User Location Change</h1>

<%= render 'form' %>

<%= link_to 'Back', user_location_changes_path %>

app/views/user_location_changes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_location_change.user %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user_location_change.location %>
</p>

<%= link_to 'Edit', edit_user_location_change_path(@user_location_change) %> |
<%= link_to 'Back', user_location_changes_path %>