config/routes.rb
Rails.application.routes.draw do
  resources :friends_rankings
  resources :discount_votes
  resources :user_location_changes
  resources :user_searches
  resources :discount_searches
  resources :user_sessions, only: [:create, :update]
  resources :friendships
  resources :discounts
  resources :settings
  resources :users

  # Routes for testing
  if Rails.env.test?
    post 'test' => 'testing#test'
    get  'test' => 'testing#test'
  end
end

app/models/discount_search.rb
class DiscountSearch < ActiveRecord::Base
  belongs_to :user
  belongs_to :location

  accepts_nested_attributes_for :location

  before_create :set_result

  def set_result
    self.result = discounts_to_builder(perform_search).target!
  end

  def perform_search
    relation = if query.present?
      Discount.where('title LIKE :query OR description LIKE :query OR category LIKE :query', query: "%#{query}%")
    else
      Discount.all
    end

    relation = relation.includes(:location)

    if location.present?
      relation = relation.where(location_id: Location.in_radius(location))
    end

    if by_friends_of.present?
      friends_ids = User.find(by_friends_of).friends.map(&:id).uniq + [by_friends_of]
      relation = relation.where(user_id: friends_ids)
    end

    relation
  end

  def discounts_to_builder(discounts)
    Jbuilder.new do |json|
      json.array! discounts do |discount|
        json.extract! discount, :id, :title
        json.location discount.location, :lat, :lng if discount.location
      end
    end
  end
end

app/controllers/discount_searches_controller.rb
class DiscountSearchesController < ApplicationController
  before_action :check_user_session
  before_action :set_discount_search, only: [:show, :edit, :update, :destroy]

  # GET /discount_searches
  # GET /discount_searches.json
  def index
    @discount_searches = DiscountSearch.all
  end

  # GET /discount_searches/1
  # GET /discount_searches/1.json
  def show
  end

  # GET /discount_searches/new
  def new
    @discount_search = DiscountSearch.new
  end

  # GET /discount_searches/1/edit
  def edit
  end

  # POST /discount_searches
  # POST /discount_searches.json
  def create
    @discount_search = DiscountSearch.new(discount_search_params)

    respond_to do |format|
      if @discount_search.save
        format.html { redirect_to @discount_search, notice: 'Discount search was successfully created.' }
        format.json { render :show, status: :created, location: @discount_search }
      else
        format.html { render :new }
        format.json { render json: @discount_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discount_searches/1
  # PATCH/PUT /discount_searches/1.json
  def update
    respond_to do |format|
      if @discount_search.update(discount_search_params)
        format.html { redirect_to @discount_search, notice: 'Discount search was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount_search }
      else
        format.html { render :edit }
        format.json { render json: @discount_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discount_searches/1
  # DELETE /discount_searches/1.json
  def destroy
    @discount_search.destroy
    respond_to do |format|
      format.html { redirect_to discount_searches_url, notice: 'Discount search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount_search
      @discount_search = DiscountSearch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discount_search_params
      params.require(:discount_search).permit(:query, :result, :user_id,
        :by_friends_of, location_attributes: [:lat, :lng, :radius])
    end
end

app/helpers/discount_searches_helper.rb
module DiscountSearchesHelper
end

app/views/discount_searches/_form.html.erb
<%= form_for(@discount_search) do |f| %>
  <% if @discount_search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discount_search.errors.count, "error") %> prohibited this discount_search from being saved:</h2>

      <ul>
      <% @discount_search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :query %><br>
    <%= f.text_area :query %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_area :result %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discount_searches/edit.html.erb
<h1>Editing Discount Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @discount_search %> |
<%= link_to 'Back', discount_searches_path %>

app/views/discount_searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Discount Searches</h1>

<table>
  <thead>
    <tr>
      <th>Query</th>
      <th>Result</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discount_searches.each do |discount_search| %>
      <tr>
        <td><%= discount_search.query %></td>
        <td><%= discount_search.result %></td>
        <td><%= discount_search.user %></td>
        <td><%= link_to 'Show', discount_search %></td>
        <td><%= link_to 'Edit', edit_discount_search_path(discount_search) %></td>
        <td><%= link_to 'Destroy', discount_search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discount search', new_discount_search_path %>

app/views/discount_searches/new.html.erb
<h1>New Discount Search</h1>

<%= render 'form' %>

<%= link_to 'Back', discount_searches_path %>

app/views/discount_searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Query:</strong>
  <%= @discount_search.query %>
</p>

<p>
  <strong>Result:</strong>
  <%= @discount_search.result %>
</p>

<p>
  <strong>User:</strong>
  <%= @discount_search.user %>
</p>

<%= link_to 'Edit', edit_discount_search_path(@discount_search) %> |
<%= link_to 'Back', discount_searches_path %>